const common = {
  description:
    "A lightweight, usually knitted, pullover shirt, close-fitting and with a round neckline and short sleeves, worn as an undershirt or outer garment.",
  stock: 100,
  sold: 0,
  rating: 4.5,
  reviews: [],
  featured: true,
};

const womenTopwear = [
  {
    category: "women",
    name: "Women Round Neck Cotton Top",
    price: 100,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img1.png"],
    sizes: ["S", "M", "L"],
    date: "2024-05-26T12:32:25.448Z",
    bestseller: true,
  },
  {
    category: "Women",
    name: "Women Round Neck Cotton Top",
    price: 130,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img5.png"],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:12:25.448Z",
    bestseller: true,
  },
  {
    category: "Women",
    name: "Women Round Neck Cotton Top",
    price: 120,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img11.png"],
    sizes: ["S", "M", "L"],
    date: "2024-05-26T09:12:25.448Z",
    bestseller: false,
  },
  {
    category: "Women",
    name: "Women Round Neck Cotton Top",
    price: 180,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img15.png"],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:12:25.448Z",
    bestseller: false,
  },
  {
    category: "Women",
    name: "Women Round Neck Cotton Top",
    price: 240,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img21.png"],
    sizes: ["S", "M", "L"],
    date: "2024-05-26T09:12:25.448Z",
    bestseller: false,
  },
  {
    category: "Women",
    name: "Women Round Neck Cotton Top",
    price: 280,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img25.png"],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:12:25.448Z",
    bestseller: false,
  },
  {
    category: "Women",
    name: "Women Round Neck Cotton Top",
    price: 340,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img31.png"],
    sizes: ["S", "M", "L"],
    date: "2024-05-26T09:12:25.448Z",
    bestseller: false,
  },
  {
    category: "Women",
    name: "Women Round Neck Cotton Top",
    price: 380,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img35.png"],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:12:25.448Z",
    bestseller: false,
  },
  {
    category: "Women",
    name: "Women Round Neck Cotton Top",
    price: 440,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img41.png"],
    sizes: ["S", "M", "L"],
    date: "2024-05-26T09:12:25.448Z",
    bestseller: false,
  },
  {
    category: "Women",
    name: "Women Round Neck Cotton Top",
    price: 480,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img45.png"],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:12:25.448Z",
    bestseller: false,
  },
  {
    category: "Women",
    name: "Women Round Neck Cotton Top",
    price: 540,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img51.png"],
    sizes: ["S", "M", "L"],
    date: "2024-05-26T09:12:25.448Z",
    bestseller: false,
  },
];

const menTopwear = [
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 200,
    subCategory: "Bottomwear",
    image: [
      "https://vault-vogue-expressjs.vercel.app/p_img2_1.png",
      "https://vault-vogue-expressjs.vercel.app/p_img2_2.png",
      "https://vault-vogue-expressjs.vercel.app/p_img2_3.png",
      "https://vault-vogue-expressjs.vercel.app/p_img2_4.png",
    ],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:02:25.448Z",
    bestseller: true,
  },
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 140,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img8.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:12:25.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 110,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img4.png"],
    sizes: ["S", "M", "XXL"],
    date: "2024-05-26T09:02:25.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 150,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img12.png"],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:02:25.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 170,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img14.png"],
    sizes: ["S", "M", "XXL"],
    date: "2024-05-26T09:02:25.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 210,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img18.png"],
    sizes: ["S", "M", "L", "XL"],
    date: "2024-05-26T09:12:25.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 250,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img22.png"],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:02:25.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 270,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img24.png"],
    sizes: ["S", "M", "XXL"],
    date: "2024-05-26T09:02:25.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 310,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img28.png"],
    sizes: ["S", "M", "L", "XL"],
    date: "2024-05-26T09:12:25.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 350,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img32.png"],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:02:25.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 370,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img34.png"],
    sizes: ["S", "M", "XXL"],
    date: "2024-05-26T09:02:25.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 410,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img38.png"],
    sizes: ["S", "M", "L", "XL"],
    date: "2024-05-26T09:12:25.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 450,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img42.png"],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:02:25.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 470,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img44.png"],
    sizes: ["S", "M", "XXL"],
    date: "2024-05-26T09:02:25.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 510,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img48.png"],
    sizes: ["S", "M", "L", "XL"],
    date: "2024-05-26T09:12:25.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Round Neck Pure Cotton T-shirt",
    price: 550,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img52.png"],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:02:25.448Z",
    bestseller: false,
  },
];

const kidsTopwear = [
  {
    category: "Kids",
    name: "Girls Round Neck Cotton Top",
    price: 140,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img6.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:23:43.448Z",
    bestseller: true,
  },
  {
    category: "Kids",
    name: "Girls Round Neck Cotton Top",
    price: 220,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img3.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-22T12:32:25.448Z",
    bestseller: false,
  },
  {
    category: "Kids",
    name: "Girls Round Neck Cotton Top",
    price: 100,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img9.png"],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:00:35.448Z",
    bestseller: false,
  },
  {
    category: "Kids",
    name: "Girls Round Neck Cotton Top",
    price: 160,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img13.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-22T12:32:25.448Z",
    bestseller: false,
  },
  {
    category: "Kids",
    name: "Girls Round Neck Cotton Top",
    price: 190,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img16.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:23:43.448Z",
    bestseller: false,
  },
  {
    category: "Kids",
    name: "Girls Round Neck Cotton Top",
    price: 220,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img19.png"],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:00:35.448Z",
    bestseller: false,
  },
  {
    category: "Kids",
    name: "Girls Round Neck Cotton Top",
    price: 260,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img23.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-22T12:32:25.448Z",
    bestseller: false,
  },
  {
    category: "Kids",
    name: "Girls Round Neck Cotton Top",
    price: 290,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img26.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:23:43.448Z",
    bestseller: false,
  },
  {
    category: "Kids",
    name: "Girls Round Neck Cotton Top",
    price: 320,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img29.png"],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:00:35.448Z",
    bestseller: false,
  },
  {
    category: "Kids",
    name: "Girls Round Neck Cotton Top",
    price: 360,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img33.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-22T12:32:25.448Z",
    bestseller: false,
  },
  {
    category: "Kids",
    name: "Girls Round Neck Cotton Top",
    price: 390,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img36.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:23:43.448Z",
    bestseller: false,
  },
  {
    category: "Kids",
    name: "Girls Round Neck Cotton Top",
    price: 420,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img39.png"],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:00:35.448Z",
    bestseller: false,
  },
  {
    category: "Kids",
    name: "Girls Round Neck Cotton Top",
    price: 460,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img43.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-22T12:32:25.448Z",
    bestseller: false,
  },
  {
    category: "Kids",
    name: "Girls Round Neck Cotton Top",
    price: 490,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img46.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:23:43.448Z",
    bestseller: false,
  },
  {
    category: "Kids",
    name: "Girls Round Neck Cotton Top",
    price: 520,
    subCategory: "Topwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img49.png"],
    sizes: ["M", "L", "XL"],
    date: "2024-05-26T09:00:35.448Z",
    bestseller: false,
  },
];

const menBottomwear = [
  {
    category: "Men",
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 190,
    subCategory: "Bottomwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img7.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:05:42.448Z",
    bestseller: true,
  },
  {
    category: "Men",
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 110,
    subCategory: "Bottomwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img10.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:23:55.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 200,
    subCategory: "Bottomwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img17.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:05:42.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 230,
    subCategory: "Bottomwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img20.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:23:55.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 300,
    subCategory: "Bottomwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img27.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:05:42.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 330,
    subCategory: "Bottomwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img30.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:23:55.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 400,
    subCategory: "Bottomwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img37.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:05:42.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 430,
    subCategory: "Bottomwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img40.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:23:55.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 500,
    subCategory: "Bottomwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img47.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:05:42.448Z",
    bestseller: false,
  },
  {
    category: "Men",
    name: "Men Tapered Fit Flat-Front Trousers",
    price: 530,
    subCategory: "Bottomwear",
    image: ["https://vault-vogue-expressjs.vercel.app/p_img50.png"],
    sizes: ["S", "L", "XL"],
    date: "2024-05-26T09:23:55.448Z",
    bestseller: false,
  },
];

const normalizeKey = (value) => value.trim().toLowerCase();

const defaultOwnerUserId = ObjectId();
const defaultSellerId = ObjectId();

db.users.insertOne({
  _id: defaultOwnerUserId,
  email: "seed.seller@vaultvogue.com",
  passwordHash: "$2b$12$gmaZ5LBdfNgiWwAD/59ZDuzor8e4bsgMjV5Qgmf2qfJDVEWZoVKeG",
  fullName: "Vault Vogue Seed Seller",
  role: "admin",
  isActive: true,
  createdAt: new Date(),
  updatedAt: new Date(),
});

db.sellers.insertOne({
  _id: defaultSellerId,
  name: "Vault Vogue Default Seller",
  ownerUserId: defaultOwnerUserId,
  contactEmail: "seed.seller@vaultvogue.com",
  passwordHash: "$2b$12$gmaZ5LBdfNgiWwAD/59ZDuzor8e4bsgMjV5Qgmf2qfJDVEWZoVKeG",
  isVerified: true,
  isActive: true,
  averageRating: 0,
  ratingCount: 0,
  createdAt: new Date(),
  updatedAt: new Date(),
});

const categoryDocs = [
  { _id: ObjectId(), name: "Women", slug: "women" },
  { _id: ObjectId(), name: "Men", slug: "men" },
  { _id: ObjectId(), name: "Kids", slug: "kids" },
];

db.categories.insertMany(categoryDocs);

const categoryBySlug = Object.fromEntries(
  categoryDocs.map((category) => [category.slug, category]),
);

const subCategoryDocs = [
  {
    _id: ObjectId(),
    categoryId: categoryBySlug.women._id,
    name: "Topwear",
    code: "women-topwear",
  },
  {
    _id: ObjectId(),
    categoryId: categoryBySlug.men._id,
    name: "Topwear",
    code: "men-topwear",
  },
  {
    _id: ObjectId(),
    categoryId: categoryBySlug.men._id,
    name: "Bottomwear",
    code: "men-bottomwear",
  },
  {
    _id: ObjectId(),
    categoryId: categoryBySlug.kids._id,
    name: "Topwear",
    code: "kids-topwear",
  },
];

db.subcategories.insertMany(subCategoryDocs);

const subCategoryByCode = Object.fromEntries(
  subCategoryDocs.map((subCategory) => [subCategory.code, subCategory]),
);

const products = [];
const inventories = [];

[
  ...womenTopwear,
  ...menTopwear,
  ...kidsTopwear,
  ...menBottomwear,
].forEach((product, index) => {
  const categorySlug = normalizeKey(product.category);
  const subCategoryCode = `${categorySlug}-${normalizeKey(product.subCategory)}`;
  const category = categoryBySlug[categorySlug];
  const subCategory = subCategoryByCode[subCategoryCode];

  const productId = ObjectId();
  const inventoryId = ObjectId();

  inventories.push({
    _id: inventoryId,
    productId: productId,
    items: product.sizes.map(size => ({
      size,
      quantity: 100,
      updatedAt: new Date(product.date)
    })),
    createdAt: new Date(product.date),
    updatedAt: new Date(product.date)
  });

  products.push({
    _id: productId,
    sellerId: defaultSellerId,
    name: product.name,
    description: common.description,
    price: product.price,
    sku: `seed-${String(index + 1).padStart(3, "0")}`,
    categoryIds: [category._id],
    subCategoryId: subCategory?._id,
    sizes: product.sizes,
    inventoryId: inventoryId,
    images: product.image.map((url, imageIndex) => ({
      url,
      isPrimary: imageIndex === 0,
    })),
    isActive: true,
    bestseller: !!product.bestseller,
    trending: false,
    details: {},
    createdAt: new Date(product.date),
  });
});

db.inventories.insertMany(inventories);
db.products.insertMany(products);
